language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn build
deploy:
  provider: heroku
  app: territories-backend
  skip_cleanup: true
  api_key:
    secure: $HEROKU_API_KEY
