language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn build
deploy:
  provider: heroku
  app: territories-backend
  skip_cleanup: true
  api_key:
    secure: eLzgDIydqA49QyGNQVW2ubtPjQWg3UJ++qF+UZq15k8Ynaqa2vply15+HUzeSQfrjb/NcEy+dTxpLfmTCHrfHgmQm/As/r8f4wEWpPiDQ2xCkUDCTXzBofF2oRAy/FgcRcXF2MVG+zcQW/Bu6V9Fkg/YRKELANX3MAUSBEAUwEhHmBJuPaCd7yHYzSSexUJayxu0oEUFAwSPbKWRjNETEcSREezj1xIoX2FTm+DeElAeKlab5AkKvuZPoVARJ2Pd23j7az9yaO42wFjkezDVMzBM03vZmRuqYW6F+gWhiTc/p0pN/jv5ag9kB51LZvcuDdAb4rXW/HojcomvV+lYd7F7RJHgBFVbfbcp/S4ZjmuUVJRABjJjhFWzhU+WK3UNdBsrxDc9U4LpXsYkjw6Z+dh1jWcz76IRwv0XGupMck6UmbxKt7Al5gAHQW6r1YiwteubRfEpY1N7A6toPf6TtMJLeN+b/neZcHml+0HcfC+O2jUz/i6MAMhZQzL4Gf37YXDlj0nM4wjKwsDfl1sMvCiVQe8jeukBw468nb1QKxsj+b/QYVSgjVkDppvjvjW4croeoxImnXo/4wxpW14OaBZehgiNjcmSoJLemdvTwPkspUmCOpesjBhCSkqJ/NeGstGhzOWHSmwWob/sZcqVfLOUwwiY1WZds+eELnxDezo=
