language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn build
deploy:
  provider: heroku
  app: territories-backend
  skip_cleanup: true
  api_key:
    secure: Po652iMl8+MoJFVdKo1CnnavSlszg7AXxDSb8aKQ+h845qQJQfArZe9qG+QeHuOWxgBQUwc3EgSHy8Z1ZX+9LIt5uDKHuGTqJSx+tG43jslAa/w/lAeXWapSQNncEG9C0zZu9FK9c5ts1jRpUilfl1qwdNW3i+FeN2L7NSt8UmgknFNdC1NGN5vQ/SFv2G4oANQwrFyWqHjeWiqcT4I/b1LB4Pz70Seb4Yowlsi7hU2WB8m1TQx+byZYK0wmSalY8jP9/bQec5UNtnxXVz+MVQ8BrpjJX/Xent5MB093QdWPBs2/WCtqn/+uIjrEkMlc1BgN/5cKmFftGxu65ALgJZ6pgd85OYpeyEbMzbxAfQPmxrCtHn5fHLtEum22npr32pZVK0F6lZVnXFxkOWZvFZ904m1tM/vZE48BIfWRZQGyYbaegBIiKR7kPFgvHitifDTgdbQGqM65J0v4RMJls2VHe0Owt8rpBmcA58l/lhe0/NROJj686DAP0/WhmFFqthxTgIb2Zq8LzHyJJYR5J9k+6QKUsUPsR3Do+bSOVcLbdL1mDFur07KcbQlc4vaEbedyQEKanc9nXwwAB0vzh3LadV0LJ9mN/tO1FefDrCL3oIfjGGLxKhbCmrKAzY4OE7cHSg3UKX0fnny8oSbib1f2xhN9e4BtcdLH/s8zuGA=
